### ISSUE TITLE
Error getting History - Crash APP

### ISSUE THREAD

**Issue by caiobarreto** [andyrozman/RileyLinkAAPS#131] opened 2019-06-04 23:10 UTC
When the App is getting history from medtronic 715, when the process finished the App crash, I did a very quick debug and appear my pump sometimes return a wrong date, I ran a lot of times to create some bugs on Firebase, I think you will be able to see the error.

**Comment by andyrozman** [comment] 2019-06-05 13:45
Problem with this issue is that even looking at Logs I can't find the real error... I had 2 people with same problem and so far I couldn't reproduce, but I will look into it...

**Comment by andyrozman** [comment] 2019-06-05 16:00
Duplicate of #127

**Comment by andyrozman** [comment] 2019-06-08 17:54
It seems that problem is with Splitter from Guava, at least that is the problem on Android 6. I changed Splitter with my own implementation.

**Comment by andyrozman** [comment] 2019-06-13 15:50
Spliter replaced with my own implementation.

**Closed as completed by andyrozman** 2019-06-13 15:50 UTC
Labels: bug, Medtronic, AAPS
